# Generated by Django 5.2.4 on 2025-08-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='email',
        ),
    ]
