# Generated by Django 5.2.4 on 2025-08-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybalance',
            name='total_received',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Payment amount'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='cbu',
            field=models.CharField(help_text='CBU (Bank account number)', max_length=22, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Maximum monthly amount this recipient can receive'),
        ),
    ]
