# Generated by Django 5.2.4 on 2025-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0002_remove_specialist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecipient',
            name='cbu',
            field=models.CharField(blank=True, help_text='CBU / CVU del destinatario', max_length=22, null=True, unique=True, verbose_name='CBU / CVU'),
        ),
    ]
