# Generated by Django 5.2.4 on 2025-08-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0002_alter_monthlybalance_total_received_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentrecipient',
            constraint=models.UniqueConstraint(fields=('priority_order',), name='unique_priority_order'),
        ),
    ]
