# Generated by Django 5.2.4 on 2025-08-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0003_paymentrecipient_unique_priority_order'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentrecipient',
            name='unique_priority_order',
        ),
    ]
