# Generated by Django 5.2.4 on 2025-08-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0003_alter_paymentrecipient_cbu'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='min_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Monto mínimo requerido por pago para ser asignado (0 = sin mínimo)', verbose_name='Mínimo por pago'),
        ),
    ]
