# Generated by Django 5.2.4 on 2025-08-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0004_remove_paymentrecipient_unique_priority_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Monthly amount this recipient can receive', verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='priority_order',
            field=models.PositiveIntegerField(default=1, help_text='Priority order for automatic selection (lower number = higher priority)', verbose_name='Order'),
        ),
    ]
