# Generated by Django 5.2.4 on 2025-08-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0004_paymentrecipient_min_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecipient',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Monto máximo que el destinatario puede recibir', verbose_name='Monto máximo'),
        ),
    ]
