# Generated by Django 5.2.4 on 2025-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0005_alter_payment_options_remove_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybalance',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Balance Mensual', 'verbose_name_plural': 'Balances Mensuales'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecipient',
            options={'ordering': ['priority_order', 'name'], 'verbose_name': 'Destinatario', 'verbose_name_plural': 'Destinatarios'},
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Monthly amount this recipient can receive', verbose_name='Salario'),
        ),
    ]
