# Generated by Django 5.2.4 on 2025-08-06 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0006_alter_monthlybalance_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecipient',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Nombre del Banco o billetera virtual', max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(help_text='Monto del pago', verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about this payment', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='operator_user',
            field=models.ForeignKey(help_text='Operador que registró este pago', on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_recipient',
            field=models.ForeignKey(help_text='Destinatario del pago', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment_instructions.paymentrecipient', verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment_file',
            field=models.FileField(blank=True, help_text='Subir comprobante de pago (imagen o PDF)', null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='alias',
            field=models.CharField(help_text='Alias del destinatario', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='cbu',
            field=models.CharField(help_text='CBU / CVU del destinatario', max_length=22, unique=True, verbose_name='CBU / CVU'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si es Verdadero, el destinatario puede recibir pagos. Si es Falso, el destinatario no puede recibir pagos', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Si es Verdadero, se reinicia mensualmente. Si es Falso, es un pago único', verbose_name='Recurrente'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='max_amount',
            field=models.PositiveIntegerField(help_text='Monto que el destinatario puede recibir', verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='name',
            field=models.CharField(help_text='Nombre del destinatario', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='priority_order',
            field=models.PositiveIntegerField(default=1, help_text='Orden de prioridad para la selección automática (Menor numero es mayor prioridad)', verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='paymentrecipient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('operator', 'Operator')], default='operator', help_text='Rol del usuario', max_length=20),
        ),
    ]
