# Generated by Django 5.2.4 on 2025-08-06 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0007_paymentrecipient_bank_name_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del banco o billetera virtual', max_length=100, unique=True, verbose_name='Nombre del Banco')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='paymentrecipient',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='paymentrecipient',
            name='bank',
            field=models.ForeignKey(blank=True, help_text='Banco o billetera virtual del destinatario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_recipients', to='payment_instructions.bank', verbose_name='Banco'),
        ),
    ]
