# Generated by Django 5.2.4 on 2025-08-24 00:38

import payment_instructions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0008_bank_remove_paymentrecipient_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre el pago', verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment_file',
            field=models.FileField(blank=True, help_text='Subir comprobante de pago (imagen o PDF)', null=True, upload_to=payment_instructions.models.modify_file_name, verbose_name='Comprobante'),
        ),
    ]
