# Generated by Django 5.2.4 on 2025-08-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0009_alter_payment_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBalance',
        ),
    ]
