# Generated by Django 5.2.4 on 2025-08-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0010_delete_monthlybalance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecipient',
            name='bank',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
