# Generated by Django 5.2.4 on 2025-08-25 00:16

import payment_instructions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_instructions', '0011_remove_paymentrecipient_bank_delete_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_payment_file',
            field=models.FileField(help_text='Subir comprobante de pago (imagen o PDF)', upload_to=payment_instructions.models.modify_file_name, verbose_name='Comprobante'),
        ),
    ]
